# Generated by Django 4.2.17 on 2025-04-11 15:14

from django.db import migrations
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtailstreamforms.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("microsite", "0116_alter_generalpurposepage_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "article",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(max_length=150, required=False)),
                                (
                                    "heading_level",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[("h2", "Heading Level 2"), ("h3", "Heading Level 3"), ("h4", "Heading Level 4")],
                                        help_text="Remember to respect best practices around hierarchy of heading level: <a href='https://developer.mozilla.org/docs/Web/HTML/Element/Heading_Elements#usage_notes'>See MDN</a>",
                                    ),
                                ),
                                (
                                    "heading_size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[("", "Large"), ("mzp-u-title-md", "Medium"), ("mzp-u-title-sm", "Small")],
                                        help_text="Sets the display size of the heading independent of the heading level (h2, h3, or h4).",
                                        required=False,
                                    ),
                                ),
                                (
                                    "alignment",
                                    wagtail.blocks.ChoiceBlock(blank=True, choices=[("", "Default"), ("t-align-center", "Center")], required=False),
                                ),
                                (
                                    "intro_para",
                                    wagtail.blocks.CharBlock(
                                        help_text="Rendered as a single styled paragraph element. 2000 chars max, but less is better.",
                                        max_length=1000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "body",
                                    wagtail.blocks.RichTextBlock(
                                        features=["h2", "h3", "bold", "italic", "strikethrough", "code", "blockquote", "link", "ol", "ul"]
                                    ),
                                ),
                            ],
                            help_text="<a href='https://protocol.mozilla.org/components/detail/article.html'>Protocol docs for article</a>.",
                            label="Article block",
                            label_format="Article: {header}",
                            required=False,
                        ),
                    ),
                    (
                        "columns",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(max_length=100, required=False)),
                                (
                                    "layout_size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[
                                            ("", "N/A"),
                                            ("mzp-t-content-md", "Medium"),
                                            ("mzp-t-content-lg", "Large"),
                                            ("mzp-t-content-xl", "Extra-large"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "column_layout",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            (" ", "One column"),
                                            ("mzp-l-columns mzp-t-columns-two", "Two column"),
                                            ("mzp-l-columns mzp-t-columns-three", "Three column"),
                                            ("mzp-l-columns mzp-t-columns-four", "Four column"),
                                        ]
                                    ),
                                ),
                                (
                                    "color_theme",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("mzp-t-light", "mzp-t-light"),
                                            ("mzp-t-dark", "mzp-t-dark"),
                                            ("mzp-t-light bb-t-light-color-01", "bb-t-light-color-01"),
                                            ("mzp-t-dark bb-t-dark-color-01", "bb-t-dark-color-01"),
                                            ("mzp-t-light bb-t-light-color-02", "bb-t-light-color-02"),
                                            ("mzp-t-dark bb-t-dark-color-02", "bb-t-dark-color-02"),
                                            ("mzp-t-light bb-t-light-color-03", "bb-t-light-color-03"),
                                            ("mzp-t-dark bb-t-dark-color-03", "bb-t-dark-color-03"),
                                            ("mzp-t-light bb-t-light-color-04", "bb-t-light-color-04"),
                                            ("mzp-t-dark bb-t-dark-color-04", "bb-t-dark-color-04"),
                                            ("mzp-t-light bb-t-light-color-05", "bb-t-light-color-05"),
                                            ("mzp-t-dark bb-t-dark-color-05", "bb-t-dark-color-05"),
                                            ("mzp-t-light bb-t-light-color-06", "bb-t-light-color-06"),
                                            ("mzp-t-dark bb-t-dark-color-06", "bb-t-dark-color-06"),
                                            ("mzp-t-light bb-t-light-color-07", "bb-t-light-color-07"),
                                            ("mzp-t-dark bb-t-dark-color-07", "bb-t-dark-color-07"),
                                        ]
                                    ),
                                ),
                                (
                                    "content",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "stack_of_pictos",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        ("title", wagtail.blocks.CharBlock(max_length=100, required=False)),
                                                        (
                                                            "pictos",
                                                            wagtail.blocks.ListBlock(
                                                                wagtail.blocks.StructBlock(
                                                                    [
                                                                        (
                                                                            "layout",
                                                                            wagtail.blocks.ChoiceBlock(
                                                                                choices=[
                                                                                    ("", "Standard"),
                                                                                    ("mzp-t-picto-center", "Centered"),
                                                                                    ("mzp-t-picto-side", "Side"),
                                                                                ],
                                                                                required=False,
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "image",
                                                                            wagtail.blocks.StructBlock(
                                                                                [
                                                                                    (
                                                                                        "image",
                                                                                        wagtail.images.blocks.ImageChooserBlock(required=False),
                                                                                    ),
                                                                                    (
                                                                                        "alt_text",
                                                                                        wagtail.blocks.CharBlock(
                                                                                            label="Alt-text for this image",
                                                                                            max_length=250,
                                                                                            required=False,
                                                                                        ),
                                                                                    ),
                                                                                    (
                                                                                        "decorative_only",
                                                                                        wagtail.blocks.BooleanBlock(
                                                                                            default=False,
                                                                                            label="Is this image decorative only?",
                                                                                            required=False,
                                                                                        ),
                                                                                    ),
                                                                                ],
                                                                                help_text="Picto block images should usually be a small icon, but larger images or (eventually) even videos can be accommodated in some layouts",
                                                                                required=True,
                                                                            ),
                                                                        ),
                                                                        ("heading", wagtail.blocks.CharBlock(max_length=100, required=False)),
                                                                        (
                                                                            "body",
                                                                            wagtail.blocks.RichTextBlock(
                                                                                features=["bold", "italic", "strikethrough", "link", "ol", "ul"],
                                                                                help_text="Don’t use this component for long-form content; it’s only for blurbs.",
                                                                                max_length=500,
                                                                                required=False,
                                                                            ),
                                                                        ),
                                                                    ]
                                                                ),
                                                                collapsed=False,
                                                            ),
                                                        ),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "picto",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "layout",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    ("", "Standard"),
                                                                    ("mzp-t-picto-center", "Centered"),
                                                                    ("mzp-t-picto-side", "Side"),
                                                                ],
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "image",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                                                                    (
                                                                        "alt_text",
                                                                        wagtail.blocks.CharBlock(
                                                                            label="Alt-text for this image", max_length=250, required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "decorative_only",
                                                                        wagtail.blocks.BooleanBlock(
                                                                            default=False, label="Is this image decorative only?", required=False
                                                                        ),
                                                                    ),
                                                                ],
                                                                help_text="Picto block images should usually be a small icon, but larger images or (eventually) even videos can be accommodated in some layouts",
                                                                required=True,
                                                            ),
                                                        ),
                                                        ("heading", wagtail.blocks.CharBlock(max_length=100, required=False)),
                                                        (
                                                            "body",
                                                            wagtail.blocks.RichTextBlock(
                                                                features=["bold", "italic", "strikethrough", "link", "ol", "ul"],
                                                                help_text="Don’t use this component for long-form content; it’s only for blurbs.",
                                                                max_length=500,
                                                                required=False,
                                                            ),
                                                        ),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "picto_with_link",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "layout",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    ("", "Standard"),
                                                                    ("mzp-t-picto-center", "Centered"),
                                                                    ("mzp-t-picto-side", "Side"),
                                                                ],
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "image",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                                                                    (
                                                                        "alt_text",
                                                                        wagtail.blocks.CharBlock(
                                                                            label="Alt-text for this image", max_length=250, required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "decorative_only",
                                                                        wagtail.blocks.BooleanBlock(
                                                                            default=False, label="Is this image decorative only?", required=False
                                                                        ),
                                                                    ),
                                                                ],
                                                                help_text="Picto block images should usually be a small icon, but larger images or (eventually) even videos can be accommodated in some layouts",
                                                                required=True,
                                                            ),
                                                        ),
                                                        ("heading", wagtail.blocks.CharBlock(max_length=100, required=False)),
                                                        (
                                                            "body",
                                                            wagtail.blocks.RichTextBlock(
                                                                features=["bold", "italic", "strikethrough", "link", "ol", "ul"],
                                                                help_text="Don’t use this component for long-form content; it’s only for blurbs.",
                                                                max_length=500,
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "link",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    ("page", wagtail.blocks.PageChooserBlock(label="Page", required=False)),
                                                                    ("external_url", wagtail.blocks.URLBlock(label="External URL", required=False)),
                                                                    (
                                                                        "rel",
                                                                        wagtail.blocks.CharBlock(
                                                                            help_text="Optional 'rel' attribute. If blank, no attribute will be set",
                                                                            max_length=100,
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    ("label", wagtail.blocks.CharBlock(max_length=100, required=False)),
                                                                ],
                                                                required=False,
                                                            ),
                                                        ),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "text",
                                                wagtail.blocks.RichTextBlock(
                                                    features=["h3", "h4", "bold", "italic", "strikethrough", "link", "ol", "ul"]
                                                ),
                                            ),
                                        ],
                                        help_text="Only blocks that can fit/flow well in a multi-column layout are allowed here - e.g. Picto",
                                    ),
                                ),
                            ],
                            help_text="Column layout wrapper: <a href='https://protocol.mozilla.org/components/detail/columns--overview.html'>Protocol docs for columns</a>.. Has Picto sub-components: <a href='https://protocol.mozilla.org/components/detail/picto--default.html'>Protocol docs for picto</a>.",
                            label="Column block",
                            label_format="Column block: {column_layout}",
                            required=False,
                        ),
                    ),
                    (
                        "compact_callout",
                        wagtail.blocks.StructBlock(
                            [
                                ("headline", wagtail.blocks.CharBlock(help_text="Around 50 chars ideally. Max 100", max_length=100, required=True)),
                                (
                                    "body",
                                    wagtail.blocks.RichTextBlock(
                                        features=["bold", "italic", "strikethrough", "link", "ol", "ul"],
                                        help_text="Around 150 chars ideally. 400 is pushing it. Max is 1000 but think about how it'll look on mobile, too",
                                        max_length=1000,
                                        required=True,
                                    ),
                                ),
                                (
                                    "cta",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("page", wagtail.blocks.PageChooserBlock(label="Page", required=False)),
                                            ("external_url", wagtail.blocks.URLBlock(label="External URL", required=False)),
                                            (
                                                "rel",
                                                wagtail.blocks.CharBlock(
                                                    help_text="Optional 'rel' attribute. If blank, no attribute will be set",
                                                    max_length=100,
                                                    required=False,
                                                ),
                                            ),
                                            ("button_text", wagtail.blocks.CharBlock(max_length=50, required=False)),
                                        ],
                                        required=True,
                                    ),
                                ),
                                ("theme", wagtail.blocks.ChoiceBlock(choices=[("mzp-t-light", "Light theme"), ("mzp-t-dark", "Dark theme")])),
                            ],
                            help_text="<a href='https://protocol.mozilla.org/components/detail/compact-call-out--default.html'>Protocol docs for compact-callout</a>.",
                            label_format="Compact callout: {headline}",
                            required=False,
                        ),
                    ),
                    (
                        "contact_form",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "form_type",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("microsite.forms.InnovationsContactForm", "Innovations site contact form"),
                                            ("microsite.forms.MEICOContactForm", "MIECO contact form"),
                                            ("microsite.forms.BuildersChallengeForm", "Builders Challenge form"),
                                        ],
                                        help_text="Note: the recipient address for the form is defined in code, not in the CMS",
                                    ),
                                ),
                                ("title", wagtail.blocks.CharBlock(max_length=120)),
                                ("tagline", wagtail.blocks.TextBlock(max_length=500, required=False)),
                                ("submit_button_text", wagtail.blocks.CharBlock(default="Submit", max_length=120)),
                                (
                                    "aftermatter_text",
                                    wagtail.blocks.CharBlock(
                                        default="We will only send you Mozilla-related information", max_length=120, required=False
                                    ),
                                ),
                                ("success_title", wagtail.blocks.CharBlock(default="Thanks!", max_length=120)),
                                (
                                    "success_message",
                                    wagtail.blocks.CharBlock(
                                        default="If you haven’t previously confirmed a subscription to a Mozilla-related newsletter you may have to do so. Please check your inbox or your spam filter for an email from us.",
                                        max_length=200,
                                    ),
                                ),
                                (
                                    "accompanying_image",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                                            ("alt_text", wagtail.blocks.CharBlock(label="Alt-text for this image", max_length=250, required=False)),
                                            (
                                                "decorative_only",
                                                wagtail.blocks.BooleanBlock(default=False, label="Is this image decorative only?", required=False),
                                            ),
                                        ],
                                        help_text="NB: Needs to match background colour (for now - working on a no-image variation)",
                                        required=False,
                                    ),
                                ),
                            ],
                            help_text="This form is cannot be used the same time as a Newsletter form. It is also very specific to Future.m.o",
                            label="Innovations Contact Form",
                            label_format="Innovations Contact Form: {title}",
                            required=False,
                        ),
                    ),
                    (
                        "hero",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "teaser",
                                    wagtail.blocks.CharBlock(
                                        help_text="Up to 150 characters, appears above the main heading", max_length=150, required=False
                                    ),
                                ),
                                (
                                    "main_heading",
                                    wagtail.blocks.CharBlock(
                                        help_text="Up to 75 characters. Will be the H1 of the page it's used in", max_length=75, required=True
                                    ),
                                ),
                                ("standfirst", wagtail.blocks.TextBlock(help_text="Up to 400 characters", max_length=400, required=False)),
                                (
                                    "background_image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        help_text="Optional but recommended - needs to be something that will fill well", required=False
                                    ),
                                ),
                                (
                                    "call_to_action",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("page", wagtail.blocks.PageChooserBlock(label="Page", required=False)),
                                            ("external_url", wagtail.blocks.URLBlock(label="External URL", required=False)),
                                            (
                                                "rel",
                                                wagtail.blocks.CharBlock(
                                                    help_text="Optional 'rel' attribute. If blank, no attribute will be set",
                                                    max_length=100,
                                                    required=False,
                                                ),
                                            ),
                                            ("label", wagtail.blocks.CharBlock(max_length=100, required=False)),
                                        ],
                                        help_text="Link for an optional button at the base of the hero",
                                        required=False,
                                    ),
                                ),
                                (
                                    "color_theme",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("mzp-t-light", "mzp-t-light"),
                                            ("mzp-t-dark", "mzp-t-dark"),
                                            ("mzp-t-light bb-t-light-color-01", "bb-t-light-color-01"),
                                            ("mzp-t-dark bb-t-dark-color-01", "bb-t-dark-color-01"),
                                            ("mzp-t-light bb-t-light-color-02", "bb-t-light-color-02"),
                                            ("mzp-t-dark bb-t-dark-color-02", "bb-t-dark-color-02"),
                                            ("mzp-t-light bb-t-light-color-03", "bb-t-light-color-03"),
                                            ("mzp-t-dark bb-t-dark-color-03", "bb-t-dark-color-03"),
                                            ("mzp-t-light bb-t-light-color-04", "bb-t-light-color-04"),
                                            ("mzp-t-dark bb-t-dark-color-04", "bb-t-dark-color-04"),
                                            ("mzp-t-light bb-t-light-color-05", "bb-t-light-color-05"),
                                            ("mzp-t-dark bb-t-dark-color-05", "bb-t-dark-color-05"),
                                            ("mzp-t-light bb-t-light-color-06", "bb-t-light-color-06"),
                                            ("mzp-t-dark bb-t-dark-color-06", "bb-t-dark-color-06"),
                                            ("mzp-t-light bb-t-light-color-07", "bb-t-light-color-07"),
                                            ("mzp-t-dark bb-t-dark-color-07", "bb-t-dark-color-07"),
                                        ]
                                    ),
                                ),
                                (
                                    "layout",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[("hero-section-default", "Default layout"), ("hero-section-centered", "Centered layout")]
                                    ),
                                ),
                            ],
                            help_text="Intended for use at top of the page. Works well with an SVG background image and appropriate color",
                            label_format="Hero: {main_heading}",
                            required=False,
                        ),
                    ),
                    (
                        "section_heading",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading_level",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[("h2", "Heading Level 2"), ("h3", "Heading Level 3"), ("h4", "Heading Level 4")],
                                        help_text="Remember to respect best practices around hierarchy of heading level: <a href='https://developer.mozilla.org/docs/Web/HTML/Element/Heading_Elements#usage_notes'>See MDN</a>",
                                    ),
                                ),
                                (
                                    "heading_size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[("", "Large"), ("mzp-u-title-md", "Medium"), ("mzp-u-title-sm", "Small")],
                                        help_text="Sets the display size of the heading independent of the heading level (h2, h3, or h4).",
                                        required=False,
                                    ),
                                ),
                                (
                                    "alignment",
                                    wagtail.blocks.ChoiceBlock(blank=True, choices=[("", "Default"), ("t-align-center", "Center")], required=False),
                                ),
                                ("text", wagtail.blocks.TextBlock(max_length=120, required=True)),
                            ],
                            label="Section heading",
                            label_format="Section heading: {text}",
                            required=False,
                        ),
                    ),
                    (
                        "split",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "layout_variant",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Standard"),
                                            ("mzp-l-split-reversed", "Reversed"),
                                            ("mzp-l-split-body-narrow", "Narrow body"),
                                            ("mzp-l-split-body-narrow mzp-l-split-reversed", "Narrow body, reversed"),
                                            ("mzp-l-split-body-wide", "Wide body"),
                                            ("mzp-l-split-body-wide mzp-l-split-reversed", "Wide body, reversed"),
                                            ("mzp-t-dark mzp-t-background-secondary", "Dark Background"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "content_size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[("mzp-t-content-md", "Medium"), ("mzp-t-content-lg", "Large"), ("mzp-t-content-xl", "Extra-large")],
                                    ),
                                ),
                                ("title", wagtail.blocks.CharBlock(max_length=120, required=True)),
                                (
                                    "text",
                                    wagtail.blocks.RichTextBlock(
                                        features=["bold", "italic", "strikethrough", "link", "ol", "ul"],
                                        help_text="Ideally less than 500 chars. 650 max.",
                                        max_length=650,
                                        required=True,
                                    ),
                                ),
                                (
                                    "cta_button",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("page", wagtail.blocks.PageChooserBlock(label="Page", required=False)),
                                            ("external_url", wagtail.blocks.URLBlock(label="External URL", required=False)),
                                            (
                                                "rel",
                                                wagtail.blocks.CharBlock(
                                                    help_text="Optional 'rel' attribute. If blank, no attribute will be set",
                                                    max_length=100,
                                                    required=False,
                                                ),
                                            ),
                                            ("button_text", wagtail.blocks.CharBlock(max_length=50, required=False)),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                                            ("alt_text", wagtail.blocks.CharBlock(label="Alt-text for this image", max_length=250, required=False)),
                                            (
                                                "decorative_only",
                                                wagtail.blocks.BooleanBlock(default=False, label="Is this image decorative only?", required=False),
                                            ),
                                        ],
                                        required=True,
                                    ),
                                ),
                            ],
                            help_text="Flexible short text + image component. <a href='https://protocol.mozilla.org/components/detail/split--default.html'>Protocol docs for split</a>. Not all options supported",
                            label="Split content",
                            label_format="Split: {title}",
                            required=False,
                        ),
                    ),
                    (
                        "video",
                        wagtail.blocks.StructBlock(
                            [("video", wagtail.embeds.blocks.EmbedBlock(required=True))],
                            icon="media",
                            label="Video embed",
                            label_format="Video embed: {video}",
                            required=False,
                        ),
                    ),
                    (
                        "horizontal_image",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock(required=False)),
                                ("alt_text", wagtail.blocks.CharBlock(label="Alt-text for this image", max_length=250, required=False)),
                                (
                                    "decorative_only",
                                    wagtail.blocks.BooleanBlock(default=False, label="Is this image decorative only?", required=False),
                                ),
                                (
                                    "color_theme",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("mzp-t-light", "mzp-t-light"),
                                            ("mzp-t-dark", "mzp-t-dark"),
                                            ("mzp-t-light bb-t-light-color-01", "bb-t-light-color-01"),
                                            ("mzp-t-dark bb-t-dark-color-01", "bb-t-dark-color-01"),
                                            ("mzp-t-light bb-t-light-color-02", "bb-t-light-color-02"),
                                            ("mzp-t-dark bb-t-dark-color-02", "bb-t-dark-color-02"),
                                            ("mzp-t-light bb-t-light-color-03", "bb-t-light-color-03"),
                                            ("mzp-t-dark bb-t-dark-color-03", "bb-t-dark-color-03"),
                                            ("mzp-t-light bb-t-light-color-04", "bb-t-light-color-04"),
                                            ("mzp-t-dark bb-t-dark-color-04", "bb-t-dark-color-04"),
                                            ("mzp-t-light bb-t-light-color-05", "bb-t-light-color-05"),
                                            ("mzp-t-dark bb-t-dark-color-05", "bb-t-dark-color-05"),
                                            ("mzp-t-light bb-t-light-color-06", "bb-t-light-color-06"),
                                            ("mzp-t-dark bb-t-dark-color-06", "bb-t-dark-color-06"),
                                            ("mzp-t-light bb-t-light-color-07", "bb-t-light-color-07"),
                                            ("mzp-t-dark bb-t-dark-color-07", "bb-t-dark-color-07"),
                                        ]
                                    ),
                                ),
                                ("disable_bottom_spacing", wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ],
                            help_text="Can be positioned above a hero block to add a wordmark before the hero",
                            icon="image",
                            label="Horizontal image / Wordmark",
                            label_format="Horizontal image: {image}",
                            required=False,
                        ),
                    ),
                    (
                        "custom_form",
                        wagtail.blocks.StructBlock(
                            [
                                ("form", wagtailstreamforms.blocks.FormChooserBlock()),
                                (
                                    "form_action",
                                    wagtail.blocks.CharBlock(
                                        help_text='The form post action. "" or "." for the current page or a url', required=False
                                    ),
                                ),
                                (
                                    "form_reference",
                                    wagtailstreamforms.blocks.InfoBlock(
                                        help_text="This form will be given a unique reference once saved", required=False
                                    ),
                                ),
                            ],
                            icon="radio-empty",
                            label_format="Custom form",
                            required=False,
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
